fix doc for gitips
qlik-oss/sense-installer pull request #226
Opened 2020-03-18 20:45 UTC by ffoysal

Signed-off-by: Foysal Iqbal <mqb@qlik.com>

2020-03-18 21:24 UTC, andriy-bulynko approved these changes

2020-03-18 22:55 UTC, ibiqlik commented on docs/concepts.md
> +    userName: "blblbl"
```suggestion
    userName: "my-git-user"

```

2020-03-19 09:37 UTC, ibiqlik commented on docs/concepts.md
> +    userName: "blblbl"
```suggestion
    accessToken: git-token
    userName: "git-username"

```

2020-03-19 11:43 UTC, ibiqlik requested changes
See my suggestion above

2020-03-19 13:04 UTC, merged